apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "{NAMESPACE}"
namePrefix: dev-
resources:
- ../../base
configMapGenerator:
- behavior: merge
  files:
  - config.json
  name: eshop-web-config
patches:
- path: replicaStrategy.yaml
  target:
    kind: Deployment
    name: eshop
