apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eshop
  name: eshop
spec:
  selector:
    matchLabels:
      app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
      - name: eshop
        image: {image}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/assets/config/config.json
          subPath: config.json
      volumes:
      - configMap:
          items:
          - key: config.json
            path: config.json
          name: eshop-web-config
        name: config-volume
